server:
  port: 8082

spring:
  application:
    name: log-batch-system
  main:
    allow-bean-definition-overriding: true

  config:
    import: "optional:file:.env[.properties]"
  datasource:
    driver-class-name: ${DB}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    connection-test-query: ${TEST_QUERY}
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always # 메타테이블 자동 생성 (개발용)
#      initialize-schema: never # 메타테이블 DDL 안씀

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  thymeleaf:
    cache: false
    mode: HTML

logging:
  level:
    p6spy: DEBUG

file:
  upload-dir: ${FILE_UPLOAD_DIR}

coolsms:
  api-key: ${SMS_API_KEY}
  api-secret: ${SMS_API_SECRET}
  api-sendernumber: ${SMS_API_SENDER_NUMBER}
